[server]
headless = true
runOnSave = true

[theme]
primaryColor = "#069494"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#e0e0e0"
font = "sans serif"

[client]
toolbarMode = "minimal"


